
<div class="page-wrapper-row full-height">
    <div class="page-wrapper-middle">
        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <div class="page-head">
                    <div class="container">
                        <div class="mt-element-step">
                            <div class="row step-line">
                                <div class="col-md-7">
                                    <!-- BEGIN PAGE TITLE -->
                                    <div class="page-title">
                                        <h1>Service order details
                                            <small>Service details, address and comments.</small>
                                        </h1>
                                    </div>
                                </div>
                                <div class="col-md-5">
                                    <div class="col-md-3 mt-step-col first active">
                                        <div class="mt-step-number bg-white">
                                            <i class="fa fa-list-alt"></i>
                                        </div>
                                        <div class="mt-step-title uppercase font-grey-cascade">Service</div>
                                    </div>
                                    <div class="col-md-3 mt-step-col">
                                        <div class="mt-step-number bg-white">
                                            <i class="fa fa-map-marker"></i>
                                        </div>
                                        <div class="mt-step-title uppercase font-grey-cascade">Find</div>
                                    </div>
                                    <div class="col-md-3 mt-step-col ">
                                        <div class="mt-step-number bg-white">
                                            <i class="fa fa-calendar"></i>
                                        </div>
                                        <div class="mt-step-title uppercase font-grey-cascade">Booking</div>
                                    </div>
                                    <div class="col-md-3 mt-step-col last">
                                        <div class="mt-step-number bg-white">
                                            <i class="fa fa-paypal"></i>
                                        </div>
                                        <div class="mt-step-title uppercase font-grey-cascade">Payment</div>
                                    </div>
                                </div>
                                <!-- END PAGE TITLE -->
                            </div>
                        </div>
                    </div>
                </div>
                <!-- BEGIN CONTENT BODY -->
                <!-- BEGIN PAGE CONTENT BODY -->
                <div class="page-content">
                    <div class="container">
                        <div class="page-content-inner">
                            <div class="row">


                                <div class="col-md-12">
                                        <!-- BEGIN VALIDATION STATES-->
                                        <div class="portlet light portlet-fit portlet-form ">
                                            <div class="portlet-body">
                                                <!-- BEGIN FORM-->
                                                <form action="#" class="form-horizontal" id="form_service" novalidate="novalidate" method="post">
                                                    <div class="form-body">

                                                        <div class="alert alert-danger display-hide">
                                                            <button class="close" data-close="alert"></button> You have some form errors. Please check below.
                                                        </div>

                                                        <h5>Services requested <span class="required" aria-required="true">*</span> </h5>
                                                        <div class="form-group form-md-checkboxes">

                                                            <?php
                                                            $category = "";
                                                            foreach($this->services as $service){
                                                                $i++;
                                                                ?>
                                                            <label class="col-md-2 control-label" for="form_control_1"><?php if($category!=$service->getCategory())  echo $service->getCategory(); ?></label>
                                                            <div class="col-md-10">
                                                                <div class="md-checkbox-list">
                                                                    <div class="md-checkbox">
                                                                        <input type="checkbox" name="services[]" value="<?php echo $service->getId(); ?>" id="checkbox1_<?= $i; ?>" class="md-check">
                                                                        <label for="checkbox1_<?= $i; ?>">
                                                                            <span class="inc"></span>
                                                                            <span class="check"></span>
                                                                            <span class="box"></span> <?php echo $service->getName(); ?></label>
                                                                    </div>

                                                                </div>
                                                            </div>
                                                            <?php
                                                                $category=$service->getCategory();
                                                            } ?>
                                                        </div>
                                                        <h5>Address</h5>
                                                        <div class="form-group form-md-line-input">
                                                            <label class="col-md-2 control-label" for="form_control_1">Address
                                                                <span class="required" aria-required="true">*</span>
                                                            </label>
                                                            <div class="col-md-10">
                                                                <input type="text" class="form-control" placeholder="" name="address">
                                                                <div class="form-control-focus"> </div>
                                                                <span class="help-block">enter your address</span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group form-md-line-input">
                                                            <label class="col-md-2 control-label" for="form_control_1">Postal code
                                                                <span class="required" aria-required="true">*</span>
                                                            </label>
                                                            <div class="col-md-10">
                                                                <input type="text" class="form-control" placeholder="" name="postal_code">
                                                                <div class="form-control-focus"> </div>
                                                                <span class="help-block">enter your postal code</span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group form-md-line-input">
                                                            <label class="col-md-2 control-label" for="form_control_1">City
                                                            </label>
                                                            <div class="col-md-10">
                                                                <input type="text" class="form-control" placeholder="" name="city" value="Sydney" readonly>
                                                                <div class="form-control-focus"> </div>
                                                                <span class="help-block">only Sydney</span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group form-md-line-input">
                                                            <label class="col-md-2 control-label" for="form_control_1">State
                                                            </label>
                                                            <div class="col-md-10">
                                                                <input type="text" class="form-control" placeholder="" name="state" value="New South Wales" readonly>
                                                                <div class="form-control-focus"> </div>
                                                                <span class="help-block">only NSW</span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group form-md-line-input">
                                                            <label class="col-md-2 control-label" for="form_control_1">Country
                                                            </label>
                                                            <div class="col-md-10">
                                                                <input type="text" class="form-control" placeholder="Australia" name="country" value="Australia" readonly>
                                                                <div class="form-control-focus"> </div>
                                                                <span class="help-block">only Australia</span>
                                                            </div>
                                                        </div>
                                                        <h5>More details</h5>
                                                        <div class="form-group form-md-line-input">
                                                            <label class="col-md-2 control-label" for="form_control_1">Mobile</label>
                                                            <div class="col-md-10">
                                                                <input type="text" class="form-control" placeholder="" name="mobile">
                                                                <div class="form-control-focus"> </div>
                                                                <span class="help-block">for appointment reminders and confirmations</span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group form-md-line-input">
                                                            <label class="col-md-2 control-label" for="form_control_1">Comments</label>
                                                            <div class="col-md-10">
                                                                <textarea class="form-control" name="comments" rows="3"></textarea>
                                                                <div class="form-control-focus"> </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="form-actions">
                                                        <div class="row">
                                                            <div class="col-md-12">
                                                                <button type="button" id="register-reset-btn" class="btn green btn-outline" onClick="this.form.reset()">RESET</button>
                                                                <button type="submit" class="btn green pull-right">Create Service Order</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                                <!-- END FORM-->
                                            </div>
                                        </div>
                                        <!-- END VALIDATION STATES-->
                                    <!-- END SAMPLE FORM PORTLET-->
                                </div>



                            </div>
                        </div>
                    </div>
                </div>
                <!-- END PAGE CONTENT BODY -->
                <!-- END CONTENT BODY -->
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END CONTAINER -->
    </div>
</div>