<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('The Big Salon - Hairdressers to your home.')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="The Big Salon connect happy clients with hairdressers professionaly." name="description" />
    <meta content="" name="author" />

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all')
        ->prependStylesheet($this->basePath('../assets/global/plugins/font-awesome/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('../assets/global/plugins/simple-line-icons/simple-line-icons.min.css'))
        ->prependStylesheet($this->basePath('../assets/global/plugins/bootstrap/css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('../assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css'))

        ->prependStylesheet($this->basePath('../assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css'))
        ->prependStylesheet($this->basePath('../assets/global/plugins/fullcalendar/fullcalendar.min.css'))

        ->prependStylesheet($this->basePath('../assets/global/css/components-rounded.css'))
        ->prependStylesheet($this->basePath('../assets/global/css/plugins.min.css'))

        ->prependStylesheet($this->basePath('../assets/pages/css/search.css'))
        ->prependStylesheet($this->basePath('../assets/pages/css/profile-2.min.css'))

        ->prependStylesheet($this->basePath('../assets/layouts/layout3/css/layout.css'))
        ->prependStylesheet($this->basePath('../assets/layouts/layout3/css/themes/default.min.css'))
        ->prependStylesheet($this->basePath('../assets/layouts/layout3/css/custom.min.css'))
    ?>
    <link href="../assets/pages/css/login.css" rel="stylesheet" type="text/css" />

    <link rel="shortcut icon" href="favicon.ico" /> </head>

<style>
    .btn-link {
        color: orangered;
        font-weight: 400;
        border-radius: 0;
    }
</style>
<body class="page-container-bg-solid">

<style>

    .cuadro1 {
        background: url(../../img/welcome.jpg)no-repeat;
        background-position: 100%;
        background-size: cover;
        overflow: hidden;
        border: 1px solid #EFEFEF;
        display: table;
        margin: 0 auto;
        display: table;
        height:100%;
        width: 100%;
    }
    .page-content {
        padding: 0px 0 30px;
    }
     .hstyle {
         color: orangered;
         font-weight: 400;
         border-radius: 0;
     }
    .centered {
        text-align: center;
    }
    
    .white {
        color: white;
    }
</style>

<div class="page-wrapper-row full-height">
    <div class="page-wrapper-middle">
        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <!-- BEGIN CONTENT BODY -->
                <!-- BEGIN PAGE CONTENT BODY -->
                <div class="page-content">
                    <div class="container">
                        <div class="page-content-inner">
                            <div class="row">
                                <div class="col-md-12 cuadro1">
                                    <h1 class="centered white">Hello <?= $this->user[0]->getName(); ?>, Welcome to <br>
                                    <img src="../img/logo.png" alt="TheBigSalon" class="logo-default" class="centered"></h1>
                                    <br>
                                    <h3 class="centered white">To help yu select the best Hairdresser,<br> you can select them by area, skills, price, feedback and rating.</h3>
                                    <h3 class="centered white">We remind you this service is available in the city of <b>SYDNEY</b></h3>
                                    <br>
                                    <h4 class="centered "><a href="javascript:;" class="btn red centered" onclick="window.location.href='<?php echo $this->url('dashboard'); ?>'"> Let's go
                                        <i class="fa fa-scissors"></i> </a></h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- END PAGE CONTENT BODY -->
                <!-- END CONTENT BODY -->
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END CONTAINER -->
    </div>
</div>

</body>

</html>