<style>

    .cuadro1 {
        background: url(../../img/join-image3.png)no-repeat;
        background-position: 100%;
        background-size: cover;
        overflow: hidden;
        border: 1px solid #EFEFEF;
        display: table;
        margin: 0 auto;
        display: table;
        height: 400px;
    }
    .page-content {
        padding: 0px 0 30px;
    }
    .hstyle {
        color: orangered;
        font-weight: 400;
        border-radius: 0;
    }
    .centered {
        text-align: center;
    }

    .margin_top{
        margin-top: 30px;
    }
</style>

<div class="page-wrapper-row full-height">
    <div class="page-wrapper-middle">
        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <!-- BEGIN CONTENT BODY -->
                <!-- BEGIN PAGE CONTENT BODY -->
                <div class="page-content">
                    <div class="container">
                        <div class="page-content-inner">
                            <div class="row">
                                <div class="col-md-6 cuadro1">
                                </div>
                                <div class="col-md-6">

                                    <h3 class="hstyle centered">Log in to THEBIGSALON</h3>

                                    <div class="col-md-12">

                                        <!-- BEGIN REGISTRATION FORM -->
                                        <?php
                                        $form = $this->form;
                                        $form->get('email')->setAttributes([
                                            'class'=>'form-control placeholder-no-fix',
                                            'placeholder'=>'Email'
                                        ]);
                                        $form->get('password')->setAttributes([
                                            'class'=>'form-control placeholder-no-fix',
                                            'placeholder'=>'Password'
                                        ]);
                                        $form->get('submit')->setAttributes(['class'=>'btn btn-success uppercase pull-right']);
                                        $form->prepare();

                                        ?>
                                        <?php if ($isLoginError): ?>
                                            <div class="alert alert-warning" role="alert">
                                                Incorrect login and/or password.
                                                <a href="<?= $this->url('reset-password') ?>">Forgot password?</a>
                                            </div>
                                        <?php endif; ?>
                                        <?= $this->form()->openTag($form); ?>
                                        <div class="form-group margin_top">
                                            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
                                            <div class="form-group">
                                                <?= $this->formLabel($form->get('email')); ?>
                                                <?= $this->formElement($form->get('email')); ?>
                                                <?= $this->formElementErrors($form->get('email')); ?>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <?= $this->formLabel($form->get('password')); ?>
                                            <?= $this->formElement($form->get('password')); ?>
                                            <?= $this->formElementErrors($form->get('password')); ?>
                                        </div>

                                        <div class="form-actions">
                                            <button type="submit" id="register-submit-btn" class="btn btn-success uppercase">Submit</button>
                                            <label class="rememberme check mt-checkbox mt-checkbox-outline">
                                                <?= $this->formElement($form->get('remember_me')); ?> Remember me
                                                <span></span>
                                            </label>
                                            <span class="pull-right">
                                              <a href="javascript:;" id="forget-password" class="forget-password">Forgot Password?</a>
                                            </span>
                                        </div>
                                        <?= $this->formElement($form->get('redirect_url')); ?>
                                        <?= $this->formElement($form->get('csrf')) ?>

                                        <?= $this->form()->closeTag(); ?>
                                        <hr>
                                        <!-- END REGISTRATION FORM -->
                                        <div class="login-options">
                                            <h4>or login with</h4>
                                            <ul class="social-icons">
                                                <li>
                                                    <a class="social-icon-color facebook" data-original-title="facebook" href="javascript:;"></a>
                                                </li>
                                                <li>
                                                    <a class="social-icon-color twitter" data-original-title="Twitter" href="javascript:;"></a>
                                                </li>
                                                <li>
                                                    <a class="social-icon-color googleplus" data-original-title="Goole Plus" href="javascript:;"></a>
                                                </li>
                                                <li>
                                                    <a class="social-icon-color linkedin" data-original-title="Linkedin" href="javascript:;"></a>
                                                </li>
                                            </ul>
                                        </div>

                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- END PAGE CONTENT BODY -->
                <!-- END CONTENT BODY -->
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END CONTAINER -->
    </div>
</div>