<div class="container">
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN LOGIN FORM -->
            <?php
            $form = $this->form;
            $form->get('user')->setAttributes([
                'class'=>'form-control placeholder-no-fix',
                'placeholder'=>'User'
            ]);
            $form->get('password')->setAttributes([
                'class'=>'form-control placeholder-no-fix',
                'placeholder'=>'Password'
            ]);
            $form->get('submit')->setAttributes(['class'=>'btn btn-success uppercase pull-right']);
            $form->prepare();

            ?>
            <?= $this->form()->openTag($form); ?>
                <h1>Please sign in</h1>
                <?php if ($isLoginError): ?>
                <div class="alert alert-warning" role="alert">
                    Incorrect login and/or password.
                </div>
                <?php endif; ?>
                <div class="form-group margin_top">
                    <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
                    <div class="form-group">
                        <?= $this->formLabel($form->get('user')); ?>
                        <?= $this->formElement($form->get('user')); ?>
                        <?= $this->formElementErrors($form->get('user')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('password')); ?>
                    <?= $this->formElement($form->get('password')); ?>
                    <?= $this->formElementErrors($form->get('password')); ?>
                </div>

                <div class="form-actions">
                    <?= $this->formElement($form->get('submit')); ?>
                    <label class="rememberme check mt-checkbox mt-checkbox-outline">
                        <?= $this->formElement($form->get('remember_me')); ?> Remember me
                        <span></span>
                    </label>
                </div>

            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
