<?= $this->doctype() ;
$logged = false;
?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('The Big Salon - Hairdressers to your home.')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="The Big Salon connect happy clients with hairdressers professionaly." name="description" />
    <meta content="" name="author" />

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all')
        ->prependStylesheet($this->basePath('../assets/global/plugins/font-awesome/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('../assets/global/plugins/simple-line-icons/simple-line-icons.min.css'))
        ->prependStylesheet($this->basePath('../assets/global/plugins/bootstrap/css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('../assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css'))

        ->prependStylesheet($this->basePath('../assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css'))
        ->prependStylesheet($this->basePath('../assets/global/plugins/fullcalendar/fullcalendar.min.css'))

        ->prependStylesheet($this->basePath('../assets/global/css/components-rounded.css'))
        ->prependStylesheet($this->basePath('../assets/global/css/plugins.min.css'))

        ->prependStylesheet($this->basePath('../assets/pages/css/search.css'))
        ->prependStylesheet($this->basePath('../assets/pages/css/profile-2.min.css'))

        ->prependStylesheet($this->basePath('../assets/layouts/layout3/css/layout.css'))
        ->prependStylesheet($this->basePath('../assets/layouts/layout3/css/themes/default.min.css'))
        ->prependStylesheet($this->basePath('../assets/layouts/layout3/css/custom.min.css'))
    ?>
    <link href="../assets/pages/css/login.css" rel="stylesheet" type="text/css" />

    <link rel="shortcut icon" href="favicon.ico" /> </head>

    <style>
        .btn-link {
            color: orangered;
            font-weight: 400;
            border-radius: 0;
        }
    </style>
<body class="page-container-bg-solid">

<style>
    .page-header {
        margin: 0px;
    }

</style>

<div class="page-wrapper">
    <div class="page-wrapper-row">
        <div class="page-wrapper-top">
            <!-- BEGIN HEADER -->
            <div class="page-header">
                <!-- BEGIN HEADER TOP -->
                <div class="page-header-top">
                    <div class="container">
                        <!-- BEGIN LOGO -->
                        <div class="page-logo">
                            <?php if ($this->identity()) { ?>
                            <a href="<? echo $this->url('dashboard'); ?>">
                                <img src="../img/logo.png" alt="TheBigSalon" class="logo-default">
                            </a>
                            <?php } else { ?>
                                <a href="<? echo $this->url('home'); ?>">
                                    <img src="../img/logo.png" alt="TheBigSalon" class="logo-default">
                                </a>
                            <?php }?>
                        </div>
                        <!-- END LOGO -->
                        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
                        <a href="javascript:;" class="menu-toggler"></a>
                        <!-- END RESPONSIVE MENU TOGGLER -->
                        <!-- BEGIN TOP NAVIGATION MENU -->
                        <div class="top-menu">
                            <?php
                            if(!isset($this->showmenu)) {
                                if ($this->identity()) { ?>
                                    <button type="button" class="btn btn-link" onclick="window.location.href='<?php echo $this->url('service'); ?>'">Service</button>
                                    <button type="button" class="btn btn-link" onclick="window.location.href='<?php echo $this->url('find'); ?>'">Hairdressers</button>
                                    <button type="button" class="btn btn-link" onclick="window.location.href='/booking'">Booking</button>
                                    <button type="button" class="btn btn-link">Appointments</button>
                                <?php } else { ?>
                                    <button type="button" class="btn btn-default"
                                            onclick="window.location.href='<?php echo $this->url('login'); ?>'">LOGIN
                                    </button>
                                    <button type="button" class="btn btn-danger"
                                            onclick="window.location.href='<?php echo $this->url('users'); ?>'">JOIN THE CLUB
                                    </button>
                                    <button type="button" class="btn btn-link">Who it Works</button>
                                    <button type="button" class="btn btn-link">Hairdressers</button>
                                <?php }
                            } ?>
                            <ul class="nav navbar-nav pull-right">
                                <!-- END INBOX DROPDOWN -->
                                <? if ($this->identity()){ ?>
                                <!-- BEGIN USER LOGIN DROPDOWN -->
                                <li class="dropdown dropdown-user dropdown-dark">
                                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                        <img alt="" class="img-circle" src="../assets/layouts/layout3/img/avatar9.jpg">
                                        <span class="username username-hide-mobile"><?= $this->user[0]->getName(); ?></span>
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-default">
                                        <li>
                                            <a href="page_user_profile_1.html">
                                                <i class="icon-user"></i> My Profile </a>
                                        </li>
                                        <li>
                                            <a href="app_calendar.html">
                                                <i class="icon-calendar"></i> My account </a>
                                        </li>
                                        <li>
                                            <a href="app_inbox.html">
                                                <i class="icon-envelope-open"></i> Customer Service
                                            </a>
                                        </li>
                                        <li class="divider"> </li>
                                        <li>
                                            <a href="/logout">
                                                <i class="icon-key"></i> Log Out </a>
                                        </li>
                                    </ul>
                                </li>
                                <!-- END USER LOGIN DROPDOWN -->
                                <?php } ?>
                            </ul>
                        </div>
                        <!-- END TOP NAVIGATION MENU -->
                    </div>
                </div>
                <!-- END HEADER TOP -->
            </div>
            <!-- END HEADER -->
        </div>
    </div>

    <?= $this->content ?>

    <div class="page-wrapper-row">
        <div class="page-wrapper-bottom">
            <!-- BEGIN FOOTER -->
            <!-- BEGIN PRE-FOOTER -->
            <div class="page-prefooter">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3 col-sm-6 col-xs-12 footer-block">
                            <h2>About</h2>
                            <p> We help you to maximize your time by giving a professional custom service. </p>
                        </div>
                        <div class="col-md-3 col-sm-6 col-xs12 footer-block">
                            <h2>Subscribe Email</h2>
                            <div class="subscribe-form">
                                <form action="javascript:;">
                                    <div class="input-group">
                                        <input type="text" placeholder="mail@email.com" class="form-control">
                                        <span class="input-group-btn">
                                                    <button class="btn" type="submit">Submit</button>
                                                </span>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6 col-xs-12 footer-block">
                            <h2>Follow Us On</h2>
                            <ul class="social-icons">
                                <li>
                                    <a href="javascript:;" data-original-title="rss" class="rss"></a>
                                </li>
                                <li>
                                    <a href="javascript:;" data-original-title="facebook" class="facebook"></a>
                                </li>
                                <li>
                                    <a href="javascript:;" data-original-title="twitter" class="twitter"></a>
                                </li>
                                <li>
                                    <a href="javascript:;" data-original-title="googleplus" class="googleplus"></a>
                                </li>
                                <li>
                                    <a href="javascript:;" data-original-title="linkedin" class="linkedin"></a>
                                </li>
                                <li>
                                    <a href="javascript:;" data-original-title="youtube" class="youtube"></a>
                                </li>
                                <li>
                                    <a href="javascript:;" data-original-title="vimeo" class="vimeo"></a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-3 col-sm-6 col-xs-12 footer-block">
                            <h2>Contacts</h2>
                            <address class="margin-bottom-40"> Phone: 02 8542 1630
                                <br> Email:
                                <a href="mailto:info@metronic.com">info@thebigsalon.com.au</a>
                            </address>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END PRE-FOOTER -->
            <!-- BEGIN INNER FOOTER -->
            <div class="page-footer">
                <div class="container"> 2016 &copy; TheBigSalon.com.au By
                    <a target="_blank" href="http://facebook.com/scribano">Armando Scribano</a>
                </div>
            </div>
            <div class="scroll-to-top">
                <i class="icon-arrow-up"></i>
            </div>
            <!-- END INNER FOOTER -->
            <!-- END FOOTER -->
        </div>
    </div>
</div>

<div class="quick-nav-overlay"></div>

<? echo $this->headScript()
    ->appendFile($this->basePath('../assets/global/plugins/respond.min.js'))
    ->appendFile($this->basePath('../assets/global/plugins/excanvas.min.js'))
    ->appendFile($this->basePath('../assets/global/plugins/ie8.fix.min.js'))

    ->appendFile($this->basePath('../assets/global/plugins/jquery.min.js'))
    ->appendFile($this->basePath('../assets/global/plugins/bootstrap/js/bootstrap.min.js'))
    ->appendFile($this->basePath('../assets/global/plugins/js.cookie.min.js'))
    ->appendFile($this->basePath('../assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js'))
    ->appendFile($this->basePath('../assets/global/plugins/jquery.blockui.min.js'))
    ->appendFile($this->basePath('../assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js'))

    ->appendFile($this->basePath('../assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js'))
    ->appendFile('http://maps.google.com/maps/api/js?libraries=places&key=AIzaSyDiMHd79UoOE1HXwbXCUB9Tq7rC0hXc7iY')
    ->appendFile($this->basePath('../assets/global/plugins/gmaps/gmaps.js'))

    ->appendFile($this->basePath('../assets/global/plugins/moment.min.js'))
    ->appendFile($this->basePath('../assets/global/plugins/fullcalendar/fullcalendar.min.js'))
    ->appendFile($this->basePath('../assets/global/plugins/jquery-ui/jquery-ui.min.js'))

    ->appendFile($this->basePath('../assets/global/plugins/jquery-validation/js/jquery.validate.min.js'))
    ->appendFile($this->basePath('../assets/global/plugins/jquery-validation/js/additional-methods.min.js'))
    ->appendFile($this->basePath('../assets/global/plugins/select2/js/select2.full.min.js'))

    ->appendFile($this->basePath('../assets/global/scripts/app.min.js'))
    ->appendFile($this->basePath('../assets/apps/scripts/calendar.js'))
    ->appendFile($this->basePath('../assets/pages/scripts/search.min.js'))
    //->appendFile($this->basePath('../assets/pages/scripts/maps-google.min.js'))
    ->appendFile($this->basePath('../assets/pages/scripts/login.js'))

    ->appendFile($this->basePath('../assets/layouts/layout3/scripts/layout.min.js'))
    ->appendFile($this->basePath('../assets/layouts/layout3/scripts/demo.min.js'))
    ->appendFile($this->basePath('../assets/layouts/global/scripts/quick-sidebar.min.js'))
    ->appendFile($this->basePath('../assets/layouts/global/scripts/quick-nav.min.js'))

?>
</body>

</html>