<?= $this->doctype() ; ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('CODESTUDIO - Technical Assessment.')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="Technical Assessment" name="description" />
    <meta content="" name="author" />

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . 'favicon.ico'])
        ->prependStylesheet('https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css')
        ->prependStylesheet($this->basePath('../css/style.css'))
        ->prependStylesheet($this->basePath('../css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('../css/bootstrap-theme.min.css'))
    ?>
    <? echo $this->headScript()->appendFile($this->basePath('../js/jquery-3.1.1.min.js')); ?>
    <? echo $this->headScript()->appendFile('//cdn.datatables.net/1.10.0/js/jquery.dataTables.js'); ?>
    <? echo $this->headScript()->appendFile('//cdn.jsdelivr.net/jquery.validation/1.13.1/jquery.validate.min.js'); ?>
</head>
<body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">CODESTUDIO</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="<?php echo $this->url('home'); ?>">Gallery</a></li>
                    <li><a href="<?php echo $this->url('categories'); ?>">Admin</a></li>
                </ul>
                <?php if($this->user){ ?>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="<?php echo $this->url('logout'); ?>">Logout</a></li>
                </ul>
                <?php } else { ?>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="<?php echo $this->url('login'); ?>">Login</a></li>
                    </ul>
                <?php } ?>
            </div>
            <!--/.nav-collapse -->
        </div>
    </nav>

    <?= $this->content ?>


</body>

</html>