<!-- AIzaSyDeFxfAKIDky0oRPXJ0XNDjjDQ2lapRYAU -->

<div class="page-wrapper-row full-height">
    <div class="page-wrapper-middle">
        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <!-- BEGIN CONTENT BODY -->
                <!-- BEGIN PAGE HEAD-->
                <div class="page-head">
                    <div class="container">
                        <div class="mt-element-step">
                            <div class="row step-line">
                                <div class="col-md-7">
                                    <!-- BEGIN PAGE TITLE -->
                                    <div class="page-title">
                                        <h1>Find a Hairdresser
                                            <small>Find a hairdresser near to your area.</small>
                                        </h1>
                                    </div>
                                </div>
                                <div class="col-md-5">
                                    <div class="col-md-3 mt-step-col first done">
                                        <div class="mt-step-number bg-white">
                                            <i class="fa fa-sign-in"></i>
                                        </div>
                                        <div class="mt-step-title uppercase font-grey-cascade">Sign up</div>
                                    </div>
                                    <div class="col-md-3 mt-step-col active">
                                        <div class="mt-step-number bg-white">
                                            <i class="fa fa-map-marker"></i>
                                        </div>
                                        <div class="mt-step-title uppercase font-grey-cascade">Find</div>
                                    </div>
                                    <div class="col-md-3 mt-step-col ">
                                        <div class="mt-step-number bg-white">
                                            <i class="fa fa-calendar"></i>
                                        </div>
                                        <div class="mt-step-title uppercase font-grey-cascade">Booking</div>
                                    </div>
                                    <div class="col-md-3 mt-step-col last">
                                        <div class="mt-step-number bg-white">
                                            <i class="fa fa-paypal"></i>
                                        </div>
                                        <div class="mt-step-title uppercase font-grey-cascade">Payment</div>
                                    </div>
                                </div>
                                <!-- END PAGE TITLE -->
                            </div>
                        </div>
                    </div>
                </div>
                <!-- END PAGE HEAD-->
                <!-- BEGIN PAGE CONTENT BODY -->
                <div class="page-content">
                    <div class="container">
                        <!-- BEGIN PAGE CONTENT INNER -->
                        <div class="page-content-inner">
                            <div class="search-page search-content-1">

                                <div class="row">
                                    <div class="col-md-7">
                                        <!-- BEGIN GEOCODING PORTLET-->
                                        <div class="portlet light portlet-fit ">
                                            <div class="portlet-title">
                                                <div class="caption">
                                                    <i class=" icon-layers font-green"></i>
                                                    <span class="caption-subject font-green bold uppercase">Search by location</span>
                                                </div>
                                            </div>
                                            <div class="portlet-body">
                                                <form class="form-inline margin-bottom-10" action="#">
                                                    <div class="input-group">
                                                        <input type="text" class="form-control" id="gmap_geocoding_address" placeholder="address...">
                                                        <span class="input-group-btn">
                                                                    <button class="btn blue" id="gmap_geocoding_btn">
                                                                        <i class="fa fa-search"></i>
                                                                </span>
                                                    </div>
                                                </form>
                                                <div id="gmap_basic" class="gmaps"> </div>
                                            </div>
                                        </div>
                                        <!-- END GEOCODING PORTLET-->
                                    </div>
                                    <div class="col-md-5">
                                        <!-- BEGIN PORTLET-->
                                        <div class="portlet light ">
                                            <div class="portlet-title">
                                                <div class="caption">
                                                    <i class="icon-edit font-dark"></i>
                                                    <span class="caption-subject font-dark bold uppercase">Hairdressers in the area</span>
                                                </div>
                                            </div>
                                            <div class="portlet-body">
                                                <div class="search-container ">
                                                    <ul>
                                                        <li class="search-item clearfix">
                                                            <div class="mt-element-card mt-element-overlay">
                                                                <div class="row">
                                                                    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                                                                        <div class="mt-card-item">
                                                                            <div class="mt-card-avatar mt-overlay-1">
                                                                                <img src="../assets/pages/img/avatars/team1.jpg">
                                                                                <br>
                                                                                <a href="/booking?id=1" class="btn btn-xs red"> Book
                                                                                    <i class="fa fa-calendar"></i></a>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                    <div class="col-md-9 ">
                                                                        <div class="search-content">
                                                                            <h3>Mark Anthony</h3>
                                                                            <p class="mt-card-desc font-grey-mint">Hairdresser stylist<br>
                                                                                Availability: Mon-Fri 9am and 7pm<br>
                                                                                Travel<br>
                                                                                Reviews
                                                                            </p>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </li>

                                                        <li class="search-item clearfix">
                                                            <div class="mt-element-card mt-element-overlay">
                                                                <div class="row">
                                                                    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                                                                        <div class="mt-card-item">
                                                                            <div class="mt-card-avatar mt-overlay-1">
                                                                                <img src="../assets/pages/img/avatars/team1.jpg">
                                                                                <br>
                                                                                <a href="/booking?id=1" class="btn btn-xs red"> Book
                                                                                    <i class="fa fa-calendar"></i></a>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                    <div class="col-md-9 ">
                                                                        <div class="search-content">
                                                                            <h3>Mark Anthony</h3>
                                                                            <p class="mt-card-desc font-grey-mint">Hairdresser stylist<br>
                                                                                Availability: Mon-Fri 9am and 7pm<br>
                                                                                Travel<br>
                                                                                Reviews
                                                                            </p>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="search-pagination">
                                                <ul class="pagination">
                                                    <li class="page-active">
                                                        <a href="javascriptt:;"> 1 </a>
                                                    </li>
                                                    <li>
                                                        <a href="javascriptt:;"> 2 </a>
                                                    </li>
                                                    <li>
                                                        <a href="javascriptt:;"> 3 </a>
                                                    </li>
                                                    <li>
                                                        <a href="javascriptt:;"> 4 </a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                        <!-- END PORTLET-->
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- END PAGE CONTENT INNER -->
                    </div>
                </div>
                <!-- END PAGE CONTENT BODY -->
                <!-- END CONTENT BODY -->
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END CONTAINER -->
    </div>
</div>