<!-- BEGIN LOGIN FORM -->
<form class="login-form" action="index.html" method="post">
    <h3 class="form-title font-green">Sign In</h3>
    <div class="alert alert-danger display-hide">
        <button class="close" data-close="alert"></button>
        <span> Enter any username and password. </span>
    </div>
    <div class="form-group">
        <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
        <label class="control-label visible-ie8 visible-ie9">Username</label>
        <input class="form-control form-control-solid placeholder-no-fix" type="text" autocomplete="off" placeholder="Username" name="username" /> </div>
    <div class="form-group">
        <label class="control-label visible-ie8 visible-ie9">Password</label>
        <input class="form-control form-control-solid placeholder-no-fix" type="password" autocomplete="off" placeholder="Password" name="password" /> </div>
    <div class="form-actions">
        <button type="submit" class="btn green uppercase">Login</button>
        <label class="rememberme check mt-checkbox mt-checkbox-outline">
            <input type="checkbox" name="remember" value="1" />Remember
            <span></span>
        </label>
        <a href="javascript:;" id="forget-password" class="forget-password">Forgot Password?</a>
    </div>
    <div class="login-options">
        <h4>Or login with</h4>
        <ul class="social-icons">
            <li>
                <a class="social-icon-color facebook" data-original-title="facebook" href="javascript:;"></a>
            </li>
            <li>
                <a class="social-icon-color twitter" data-original-title="Twitter" href="javascript:;"></a>
            </li>
            <li>
                <a class="social-icon-color googleplus" data-original-title="Goole Plus" href="javascript:;"></a>
            </li>
            <li>
                <a class="social-icon-color linkedin" data-original-title="Linkedin" href="javascript:;"></a>
            </li>
        </ul>
    </div>
    <div class="create-account">
        <p>
            <a href="javascript:;" id="register-btn" class="uppercase">Create an account</a>
        </p>
    </div>
</form>
<!-- END LOGIN FORM -->
<!-- BEGIN FORGOT PASSWORD FORM -->
<form class="forget-form" action="index.html" method="post">
    <h3 class="font-green">Forget Password ?</h3>
    <p> Enter your e-mail address below to reset your password. </p>
    <div class="form-group">
        <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Email" name="email" /> </div>
    <div class="form-actions">
        <button type="button" id="back-btn" class="btn green btn-outline">Back</button>
        <button type="submit" class="btn btn-success uppercase pull-right">Submit</button>
    </div>
</form>
<!-- END FORGOT PASSWORD FORM -->
<!-- BEGIN REGISTRATION FORM -->
<?php
$form = $this->form;
$form->get('fullname')->setAttributes([
'class'=>'form-control placeholder-no-fix',
'placeholder'=>'Full Name'
]);
$form->get('email')->setAttributes([
    'class'=>'form-control placeholder-no-fix',
    'placeholder'=>'Email'
]);
$form->get('mobile')->setAttributes([
    'class'=>'form-control placeholder-no-fix',
    'placeholder'=>'Mobile'
]);
$form->get('address')->setAttributes([
    'class'=>'form-control placeholder-no-fix',
    'placeholder'=>'Address'
]);
$form->get('city')->setAttributes([
    'class'=>'form-control placeholder-no-fix',
    'placeholder'=>'City'
]);
$form->get('country')->setAttributes([
    'class'=>'form-control placeholder-no-fix',
    'placeholder'=>'Country'
]);
$form->get('username')->setAttributes([
    'class'=>'form-control placeholder-no-fix',
    'placeholder'=>'Username'
]);
$form->get('password')->setAttributes([
    'class'=>'form-control placeholder-no-fix',
    'placeholder'=>'Password'
]);
$form->get('submit')->setAttributes(['class'=>'btn btn-success uppercase pull-right']);
$form->prepare();

?>
<?= $this->form()->openTag($form); ?>
    <h3 class="font-green">Sign Up</h3>
    <p class="hint"> Enter your personal details below: </p>
    <div class="form-group">
        <div class="form-group">
            <?= $this->formLabel($form->get('fullname')); ?>
            <?= $this->formElement($form->get('fullname')); ?>
            <?= $this->formElementErrors($form->get('fullname')); ?>
        </div>
    </div>
        <div class="form-group">
            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
            <div class="form-group">
                <?= $this->formLabel($form->get('email')); ?>
                <?= $this->formElement($form->get('email')); ?>
                <?= $this->formElementErrors($form->get('email')); ?>
            </div>
        </div>
    <div class="form-group">
        <?= $this->formLabel($form->get('mobile')); ?>
        <?= $this->formElement($form->get('mobile')); ?>
        <?= $this->formElementErrors($form->get('mobile')); ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($form->get('address')); ?>
        <?= $this->formElement($form->get('address')); ?>
        <?= $this->formElementErrors($form->get('address')); ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($form->get('city')); ?>
        <?= $this->formElement($form->get('city')); ?>
        <?= $this->formElementErrors($form->get('city')); ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($form->get('country')); ?>
        <?= $this->formElement($form->get('country')); ?>
        <?= $this->formElementErrors($form->get('country')); ?>
    </div>
    <p class="hint"> Enter your account details below: </p>
    <div class="form-group">
        <?= $this->formLabel($form->get('username')); ?>
        <?= $this->formElement($form->get('username')); ?>
        <?= $this->formElementErrors($form->get('username')); ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($form->get('password')); ?>
        <?= $this->formElement($form->get('password')); ?>
        <?= $this->formElementErrors($form->get('password')); ?>
    </div>
    <div class="form-group">
        <label class="control-label visible-ie8 visible-ie9">Re-type Your Password</label>
        <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Re-type Your Password" name="rpassword" /> </div>
    <div class="form-group margin-top-20 margin-bottom-20">
        <label class="mt-checkbox mt-checkbox-outline">
            <input type="checkbox" name="tnc" /> I agree to the
            <a href="javascript:;">Terms of Service </a> &
            <a href="javascript:;">Privacy Policy </a>
            <span></span>
        </label>
        <div id="register_tnc_error"> </div>
    </div>
    <div class="form-actions">
        <button type="button" id="register-back-btn" class="btn green btn-outline">Back</button>
        <?= $this->formElement($form->get('submit')); ?>
    </div>
<?= $this->form()->closeTag(); ?>
<!-- END REGISTRATION FORM -->