
<?= $this->headLink()
->prependStylesheet('../assets/pages/css/faq.min.css'); ?>

<div class="page-wrapper-row full-height">
    <div class="page-wrapper-middle">
        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <!-- BEGIN CONTENT BODY -->
                <!-- BEGIN PAGE HEAD-->
                <div class="page-head">
                    <div class="container">
                        <!-- BEGIN PAGE TITLE -->
                        <div class="page-title">
                            <h1>Manager
                                <small>you can talk to the manager trough this section</small>
                            </h1>
                        </div>
                        <!-- END PAGE TITLE -->
                    </div>
                </div>
                <!-- END PAGE HEAD-->
                <!-- BEGIN PAGE CONTENT BODY -->
                <div class="page-content">
                    <div class="container">
                        <!-- BEGIN PAGE BREADCRUMBS -->
                        <ul class="page-breadcrumb breadcrumb">
                            <li>
                                <a href="index.html">Customer Service</a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <span>Manager</span>
                            </li>
                        </ul>
                        <!-- END PAGE BREADCRUMBS -->
                        <!-- BEGIN PAGE CONTENT INNER -->
                        <div class="page-content-inner">
                            <div class="profile">
                                <div class="tabbable-line tabbable-full-width">
                                    <ul class="nav nav-tabs">
                                        <li class="active">
                                            <a href="#tab_1_1" data-toggle="tab"> Overview </a>
                                        </li>
                                    </ul>
                                    <div class="tab-content">
                                        <div class="tab-pane active" id="tab_1_1">
                                            <div class="row">
                                                <div class="col-md-3">
                                                    <ul class="list-unstyled profile-nav">
                                                        <li>
                                                            <img src="../assets/pages/media/profile/people19.png" class="img-responsive pic-bordered" alt="" />
                                                        </li>
                                                    </ul>
                                                </div>
                                                <div class="col-md-9">
                                                    <div class="row">
                                                        <div class="col-md-8 profile-info">
                                                            <h1 class="font-green sbold uppercase">Armando Scribano</h1>
                                                            <p> Hello and thanks for using this TheBigSalon.com.au which is meant to help people like you, by optimising time and efforts. I understand that you are in this section for a reason, ok, let's see, trough this FAQ I hope we can solve your enquiry, if not you can write me a message at the end of this section.  </p>
                                                        </div>

                                                        <div class="page-content-inner">
                                                            <div class="faq-page faq-content-1">
                                                                <div class="faq-content-container">
                                                                    <div class="row">
                                                                        <div class="col-md-9">
                                                                            <div class="faq-section ">
                                                                                <h2 class="faq-title uppercase font-blue">General</h2>
                                                                                <div class="panel-group accordion faq-content" id="accordion1">
                                                                                    <div class="panel panel-default">
                                                                                        <div class="panel-heading">
                                                                                            <h4 class="panel-title">
                                                                                                <i class="fa fa-circle"></i>
                                                                                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapse_1"> How do I vote or respond to a poll?</a>
                                                                                            </h4>
                                                                                        </div>
                                                                                        <div id="collapse_1" class="panel-collapse collapse">
                                                                                            <div class="panel-body">
                                                                                                <p> Duis autem vel eum iriure dolor in hendrerit in vulputate. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut. </p>
                                                                                                <p> Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa
                                                                                                    nesciunt laborum eiusmod. </p>
                                                                                            </div>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="panel panel-default">
                                                                                        <div class="panel-heading">
                                                                                            <h4 class="panel-title">
                                                                                                <i class="fa fa-circle"></i>
                                                                                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapse_2"> Do you accept purchase orders?</a>
                                                                                            </h4>
                                                                                        </div>
                                                                                        <div id="collapse_2" class="panel-collapse collapse">
                                                                                            <div class="panel-body">
                                                                                                <p> Duis autem vel eum iriure dolor in hendrerit in vulputate. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut. </p>
                                                                                                <p> Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa
                                                                                                    nesciunt laborum eiusmod. </p>
                                                                                            </div>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="panel panel-default">
                                                                                        <div class="panel-heading">
                                                                                            <h4 class="panel-title">
                                                                                                <i class="fa fa-circle"></i>
                                                                                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapse_3"> How many responses per poll (which plan) do I need?</a>
                                                                                            </h4>
                                                                                        </div>
                                                                                        <div id="collapse_3" class="panel-collapse collapse">
                                                                                            <div class="panel-body">
                                                                                                <p> Duis autem vel eum iriure dolor in hendrerit in vulputate. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut. </p>
                                                                                                <p> Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa
                                                                                                    nesciunt laborum eiusmod. </p>
                                                                                            </div>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="panel panel-default">
                                                                                        <div class="panel-heading">
                                                                                            <h4 class="panel-title">
                                                                                                <i class="fa fa-circle"></i>
                                                                                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapse_4"> What if my audience does not have a phone or a web-enabled device with internet access?</a>
                                                                                            </h4>
                                                                                        </div>
                                                                                        <div id="collapse_4" class="panel-collapse collapse">
                                                                                            <div class="panel-body">
                                                                                                <p> Duis autem vel eum iriure dolor in hendrerit in vulputate. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut. </p>
                                                                                                <p> Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa
                                                                                                    nesciunt laborum eiusmod. </p>
                                                                                            </div>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="panel panel-default">
                                                                                        <div class="panel-heading">
                                                                                            <h4 class="panel-title">
                                                                                                <i class="fa fa-circle"></i>
                                                                                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapse_6"> How fast do responses show up?</a>
                                                                                            </h4>
                                                                                        </div>
                                                                                        <div id="collapse_6" class="panel-collapse collapse">
                                                                                            <div class="panel-body">
                                                                                                <p> Duis autem vel eum iriure dolor in hendrerit in vulputate. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut. </p>
                                                                                                <p> Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa
                                                                                                    nesciunt laborum eiusmod. </p>
                                                                                            </div>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>

                                                                        <div class="col-md-9">
                                                                            <h5>If none of those questions can help you, please send me your enquiry trough this form</h5>
                                                                            <div> Message </div>
                                                                            <div> <textarea name="message" class="form-control"> </textarea></div>
                                                                            <p class="help-block">
                                                                                <span class="label label-sm label-danger">Note:&nbsp;</span> The time to answer an enquiry could be up to 24hs. </p>
                                                                        </div>
                                                                        <div class="col-md-9">
                                                                            <button type="submit" class="btn green">Submit</button>
                                                                            <button type="button" class="btn default">Cancel</button>
                                                                        </div>

                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>




                                                    <!--end row-->
                                                </div>
                                            </div>
                                        </div>
                                        <!--end tab-pane-->
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- END PAGE CONTENT INNER -->
                    </div>
                </div>
                <!-- END PAGE CONTENT BODY -->
                <!-- END CONTENT BODY -->
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END CONTAINER -->
    </div>
</div>