<div class="jumbotron">
    <h1>Technical Assessment <br><span class="zf-green">Armando Scribano</span></h1>

    <p> * Create a web form in which a user can enter a phone number and upto 3 SMS messages worth of text </p>
    <p> * On Submission f the form search and replace any fund http url with a bitly shortlink via the Bitly API</p>
    <p> * Once the message is ready, send it to the given phone number as an sms via HTTP BurstSMS API </p>


    </p>

    </div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Form</h3>
            </div>
            <div class="panel-body">
                <?php
                $title = 'Send a SMS';
                $this->headTitle($title);
                ?>
                <h1><?php echo $this->escapeHtml($title); ?></h1>
                <?php
                $form->setAttribute('action', $this->url('home'));
                $form->prepare();

                echo $this->form()->openTag($form);
                echo $this->formRow($form->get('mobile'));
                echo $this->formRow($form->get('message'));
                echo $this->formSubmit($form->get('submit'));
                echo $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Result</h3>
            </div>
            <div class="panel-body">
                <?php
                echo "Mobile: ".$this->mobile."<br>";
                echo "Message: ".$this->message."<br>";
                echo "Status: ".$this->result;
                ?>
            </div>
        </div>
    </div>
</div>
