<style>

    .slider-slide-header {
        position: relative;
        display: inline-block;
        float: left;
        display: block;
        float: none;
        margin: 0 auto;
        padding: 0 20px;
        width: 100% !important;
        max-width: 1120px !important;
        margin-top: 40px;
    }
    h1.h1-extra {
        font-family: 'Museo W01_700', Helvetica, Arial, sans-serif;
        font-size: 32px;
        line-height: 34px;
        line-height: 40px !important;
    }
    .txt-blockHeader, .txt-blockHeader * {
        position: relative;
        display: inline-block;
        float: left;
        margin: 0 0 20px 0;
        padding: 0;
        width: 100%;
        height: auto;
        font-weight: normal;
    }
    .txt-align-center {
        text-align: center !important;
    }

</style>

<div class="page-wrapper-row full-height">
    <div class="page-wrapper-middle">
        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <!-- BEGIN CONTENT BODY -->
                <!-- BEGIN PAGE HEAD-->
                <div class="page-head">
                    <div class="container">

                        <div class="slider-scroll">
                            <div class="slider-slide slider-slide-1 txt-blu bgc-g03 bgi-crop-cover bgr-repeatoff isOption-6" id="slider-slide-1">
                                <div class="slider-slide-header">
                                    <h1 class="txt-align-center h1-extra txt-blockHeader"><p>Get Hairdressers at your home, enter to <span class="txt-org">TheBigSalon</span></p>
                                    </h1>
                                    <div class="txt-align-center"><p>Save time and money &#8211; Book ours selected Hairdressers.</p>
                                    </div>
                                    <div class="grd-row-space"></div>
                                    <p class="txt-align-center">
                                        <button type="button" class="btn btn-danger" onclick="window.location.href='<?php echo $this->url('users'); ?>'">JOIN THE CLUB</button>
                                    </p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <!-- END PAGE HEAD-->
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END CONTAINER -->
    </div>
</div>