<style>

    #flickr {
        max-width: 960px;
        text-align: center;
    }
    #flickr h3 {
        margin: 0;
        padding: 0.7em;
        background: #303030;
        color: #fff;
        font-weight: normal;
        font-size: 1em;
        text-transform: uppercase;
    }

    #flickr .images a {
        display: inline-block;
        margin: 0.5em;
    }

    #flickr .images a img {
        padding: 5px;
        border: 1px solid #ddd;
    }

</style>
<div class="container">
    <div class="page-header">
        <h1>Flickr Gallery</h1>
    </div>
    <div class="row">
        <!-- BEGIN Gallery Menu -->
        <div class="col-xs-6 col-sm-2 sidebar-offcanvas" id="sidebar">
            <div class="list-group" id="menu">
            </div>
        </div>
        <!-- END Gallery Menu -->
        <!-- BEGIN Image Gallery -->
        <div class="col-sm-6">
            <div id="flickr"></div>
        </div>
        <!-- END Image Gallery -->
        <!-- BEGIN Image Gallery -->
        <div class="col-sm-4"> <h3>Description</h3>
            <div id="description"></div>
        </div>
        <!-- END Image Gallery -->
    </div>
</div>

<script>

    (function() {
        function Flickrphotoinfo() {
            this.init();
        }

        Flickrphotoinfo.prototype = {
            init: function() {
                window.getPhotos = this.getPhotos;
                this.getCategories();
                this.getJSON();
            },
            getCategories: function(){
                var request   = $.ajax({
                    url:          'categories/getlist',
                    cache:        false,
                    dataType:     'json',
                    contentType:  'application/json; charset=utf-8',
                    type:         'get'
                });
                request.done(function(data){
                    $.each(data['data'], function(key, value) {
                        $('#menu')
                            .append($("<a href='/?category="+value[1]+"'></a>")
                                .attr("class","list-group-item")
                                .text(value[1]));
                    });
                });
                request.fail(function(jqXHR, textStatus){
                    console.log('Error');
                });
            },
            getJSON: function() {
                var src = "https://api.flickr.com/services/rest/?jsoncallback=getPhotos&page=1&method=flickr.photos.getInfo&api_key=27228e1d9df091bbad7b8682f554357f&photo_id=<?php echo $this->id; ?>&format=json";
                var script = document.createElement( "script" );
                script.src = src;
                document.body.appendChild( script );
            },
            getPhotos: function( data ) {
                var limit = 18;

                if( data && data.photo ) {
                    var photo = data.photo;
                    var html = "";
                    html += "<div class='images'>";
                    var sqr = 'https://farm' + photo.farm + '.staticflickr.com/' + photo.server +
                                '/' + photo.id + '_' + photo.secret + '_b.jpg';
                    html += "<img src='" + sqr + "' alt='' width='400'/>";
                    html += "</div>";

                    document.querySelector( "#flickr" ).innerHTML = html;
                    document.querySelector( "#description" ).innerHTML = photo.description._content;
                }
            }
        };

        document.addEventListener( "DOMContentLoaded", function() {
            var flickrFeed = new Flickrphotoinfo();

        });

    })();

</script>

</body>
</html>